[package]
name = "local-search-app"
version = "0.1.0"
authors = ["oddg <odegevigney@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
rand = { version = "0.7.0", features = [ "small_rng" ] }
stdweb = "0.4.2"
yew = "0.6.0"
